name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:
    name: deploy app
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install Dependencies
      run: npm install
    - name: deploy app
      run: npm run deploy
